Minor settings cleanup
Noloxs/hell_snake pull request #39
Opened 2024-05-27 21:36 UTC by stixes

On review, I found minor issues. a settings test did not run, and failed when activated. Fixed lead to clean-code based readability to settings constructor. Also change a settings reference to singleton use, rather than deep reference.

2024-05-27 21:36 UTC, stixes commented
Merge if happy :)

2024-05-28 14:54 UTC, Noloxs requested changes

2024-05-28 19:15 UTC, stixes commented on src/classes/settings.py
> +            self.loadDefaults()
fixed 👍

2024-05-28 21:08 UTC, Noloxs approved these changes

2024-05-28 21:08 UTC, merged